added instagram button on header
Call-for-Code-for-Racial-Justice/Five-Fifths-Voter pull request #366
Opened 2023-02-02 13:52 UTC by iamvinayvk

Signed-off-by: Vinay Kushwaha <iamvinayvk@gmail.com>

Contributes to #365 

## What did you do?
- Added the Instragam icon on the header
- Linked the Icon to the 5/5 Instagram page feed
![image](https://user-images.githubusercontent.com/51132814/216341813-08281191-b85d-49de-ba74-e53cdac3b985.png)
![image](https://user-images.githubusercontent.com/51132814/216342082-9349adc8-b0b2-4512-a3e4-2820a6efe4fb.png)

## Why did you do it?
for fixing the issue as given

## How have you tested it?
- local build
- checked on different screen sizes

## Were docs updated if needed?

- [ ] No
- [ ] Yes
- [x] N/A

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new console logs
- [x] Fixes entire issue
- [ ] Partial fix for issue

2023-02-11 17:17 UTC, GeraldMit approved these changes

2023-02-11 17:28 UTC, GeraldMit requested changes
in the current placement on desktop browsers, it isn't centered, or with other icons on the right. 
It may need a spacer from the options, or be moved to be next to Five Fifths voter itself

It isn't apparent that the Instagram account is for FiveFithsVoter, as opposed to an Instagram related to the Voter Support menu option.

2023-02-11 19:54 UTC, iamvinayvk commented
@GeraldMit made the required changes

- [x] moved the Instagram icon with other icons on the right in the header bar ( next to FifveFifthsVoter logo and language selection)


![image](https://user-images.githubusercontent.com/51132814/218278482-b71311bc-330d-448a-a3d4-0d0425dd841e.png)

![image](https://user-images.githubusercontent.com/51132814/218278518-cb15ab7c-37c2-4a1e-a790-72ad09568417.png)

2023-02-11 20:22 UTC, davidnixon commented
@iamvinayvk Thanks for the help here! 

@GeraldMit what do you think here? I like it on the header bar. There is some extra styling required because its a link on the header bar which I guess is not expected. If we end up adding more social links, maybe we can look at moving everything to a footer.

2023-02-11 20:22 UTC, davidnixon approved these changes

2023-02-12 03:11 UTC, GeraldMit approved these changes

2023-02-12 03:11 UTC, merged